project:
  type: website
  resources:
    - CNAME

website:
  title: "joshua gloor"
  description: "Joshua Gloor — data engineer in Singapore"
  site-url: https://www.gloor.fyi
  navbar:
    right:
      - text: "blog"
        href: index.qmd
      - projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/JoshuaGloor
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-gloor/
format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    highlight-style: solarized
    mainfont: "STIX Two Text"
    monofont: "Source Code Pro"